sudo: required
services:
  - docker
language: c
script:
  - docker run -e DISTRO=${DISTRO} -v `pwd`:/home/opam/src ocaml/opam2:${DISTRO} /home/opam/src/.docker.sh
env:
  matrix:
  - DISTRO="debian-stable"
  - DISTRO="alpine"
  - DISTRO="ubuntu-16.04"
  - DISTRO="ubuntu"
