sudo: required
services:
  - docker
language: c
script:
  - docker build --build-arg DISTRO=$DISTRO -f .dockerfiles/opam .
env:
  matrix:
  - DISTRO="debian-stable"
  - DISTRO="alpine"
  - DISTRO="ubuntu-16.04"
  - DISTRO="ubuntu"
